version: "3.8"

services:
  nextjs:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: local-player
    network_mode: "host"
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./videos:/opt/local-player/videos
      - /opt/local-player/node_modules
    environment: